# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: pnpm i

      - name: PNPM build
        run: pnpm run build

      - name: Publish to NPM
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    
#       - name: build
#       - uses: pnpm/action-setup@v2.2.2
#         with:
#           version: 7
          
#       - name: install
#         run: pnpm install --frozen-lockfile
#       - name: build
#         run: pnpm run build
        
#       - name: publish
#       - uses: actions/checkout@v3
#       # Setup .npmrc file to publish to npm
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '16.x'
#           registry-url: 'https://registry.npmjs.org'
#           cache: 'pnpm'
          
#       - run: pnpm publish --access public
      
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
